images_dir: data/images
masks_dir: data/masks
train_split: 250 # 0.625%
val_split: 100 # 0.25%
test_split: 50 # 0.125%

n_random_patches_per_image: 28

patch_size: 256
patch_overlap: 0.5

n_workers: 12