# Datamodule
data_path: data
images_dir: data/images
masks_dir: data/masks
split_path: data/split.json
n_random_patches_per_image: 4
patch_size: 512
overlap: 0
train_batch_size: 4
val_batch_size: 8
num_workers: 12

# Model and training
lr: 0.0001
epochs: 20


# General
train_split: 250 # 0.625%
val_split: 100 # 0.25%
test_split: 50 # 0.125%

# Run
experiment_name: 'aerial-multiclass-seg'
run_description: 'patch-size:512'

# loss_fn:
#   _target_: torch.nn.BCELoss