# @package _global_

defaults:
  - _self_
  - datamodule: default
  - backbone: unet_smp
  - module: default
  - loss: dice_loss
  - metric: dice_metric_torch
  - logger: mlflow
  - callbacks: default
  - trainer: default

core:
  name: aerial-multiclass-segm # experiment name

run_name: ${now:%Y-%m-%d_%H-%M-%S}_test

hydra:
  run:
    dir: logs/hydra/${core.name}/${run_name}
  sweep:
    dir: logs/hydra/${core.name}/${run_name}
  job:
    chdir: true # required to save checkpoint in the logs dir

best_ckp_path: '/home/gptrapletti/ds/aerial-multiclass-segm/logs/hydra/aerial-multiclass-segm/2023-12-30_18-44-06_patch:256_loss:dice_backbone:default/checkpoints/epoch=31.ckpt'


