# @package _global_

defaults:
  - _self_
  - datamodule: default
  - backbone: unet_monai # unet_smp
  - module: default
  - loss: crossentropy_torch # focal_dice
  - metric: dice_metric_torch
  - logger: mlflow
  - callbacks: default
  - trainer: default

core:
  name: aerial-multiclass-segm # experiment name

run_name: ${now:%Y-%m-%d_%H-%M-%S}_default

hydra:
  run:
    dir: logs/hydra/${core.name}/${run_name}
  sweep:
    dir: logs/hydra/${core.name}/${run_name}
  job:
    chdir: true # required to save checkpoint in the logs dir

